//! This file is generated by build.rs, do not modify

use miden_objects::{word, Word};

// KERNEL V0 PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed procedures from the kernel 0.
pub const KERNEL0_PROCEDURES: [Word; 49] = [
    // account_get_initial_commitment
    word!("0x920898348bacd6d98a399301eb308478fd32b32eab019a5a6ef7a6b44abb61f6"),
    // account_compute_current_commitment
    word!("0x5d3758f4ce60f8d489594a874f36811e8d0287af1d9fee9a82776e01b0d18319"),
    // account_get_id
    word!("0xc42de24ac12ee6edfc090f79c2e4abce896ba95dec2bd781794d7d22062b1063"),
    // account_get_nonce
    word!("0xc36235a9f8a3c3d02a6d01d203140342621851d0d10d8ce2838a3c7f92f3a0d1"),
    // account_incr_nonce
    word!("0x90ab0ffff9d2b91b9c28963e5caac1d48f24dab3a97ecbd3d9b7ae73c37da7c6"),
    // account_get_initial_code_commitment
    word!("0xcaff9917337053663a67166ce738a1fcfc14c364085e26ed7cd360f7e9aef46b"),
    // account_get_code_commitment
    word!("0x9747eb2383e5a92a948ffd27f3b9b829591da0e65209137da53cc19771b35882"),
    // account_get_initial_storage_commitment
    word!("0x5932cb0394cc85330e65e4c0325bb869ec1d08b295c310f7375076a98b143d57"),
    // account_compute_storage_commitment
    word!("0xf980f805cefb4c14f6321ac2b7b25ebbb03296db7be322b7bcc4aa3081f88146"),
    // account_get_item
    word!("0x96dea0174db0c63ecc59685a94bb708baa42494503feb31b4f589d92a78c7445"),
    // account_set_item
    word!("0x859298575d9e65d33cafeea042ab643f8e1aff18d07940ed68f2eeb567a2d11d"),
    // account_get_map_item
    word!("0x167d576f2e844a23f64475775151e5498a4c850aefcf6cabf2163d3804bb01d6"),
    // account_set_map_item
    word!("0x54d2f4bb384050b02cd8fac9bfadcde46fbffa956c6768a2de8c32adb9facfff"),
    // account_get_initial_vault_root
    word!("0x4d4d91079aaacad1bc86b29a0d61d25508ccb705c29d1b1357016f7373bf299e"),
    // account_get_vault_root
    word!("0x92316e2074777ba2bc1773dc3f69f330d7940b84d1f4bf57138f8c05c96e8e23"),
    // account_add_asset
    word!("0x62f93d9e117aa39c7575cd32d731c9852696cc9a556ce06b7ee7d263be7c90de"),
    // account_remove_asset
    word!("0x1738a745c309f5c227b41f40372752d7c177576951b94d2dc28d401b3933455c"),
    // account_get_balance
    word!("0x575792b210a0b9b0e96ab9ec971bad0b9c9993bf7447eaab1960282f4cbfed6e"),
    // account_has_non_fungible_asset
    word!("0xd7302fa4b1af71370ac3567eb87df94151151e9ce7e614541f7ee7151f7ddc48"),
    // account_compute_delta_commitment
    word!("0xa06b613dad001f5f0b72897f0deb932effc42a812a594000681bfea044e010e9"),
    // account_was_procedure_called
    word!("0x66590239c6bbad9ab08a1be9721dc753e2eb9343981fc7683654cfb7f8929c18"),
    // faucet_mint_asset
    word!("0x2242526b55cbbd553a7cb7824cacb7634c54d3d3035c1e2b5e082b6acff3a337"),
    // faucet_burn_asset
    word!("0xa188c79a39b2e18805d7c88179d71865339786e52a23633730b76cbc26ddb379"),
    // faucet_get_total_fungible_asset_issuance
    word!("0xbe40d07ea47bee3a07792d1360bc240b145baff8414e9f8b5b0e6f71f44d1469"),
    // faucet_is_non_fungible_asset_issued
    word!("0xf5ce6d77199a15e6027e2c6b78e9a3adf173cf26f7fa365d1c1d32c8e16f4208"),
    // note_get_assets_info
    word!("0xe191daee1d69fd3928353fb9802e1aa8b8a6efc217b4d64dad1eaddbdf2b50ba"),
    // note_add_asset
    word!("0x28644b5248cf97e62ec9df421bb5a79736b6e7cac77f6c19418437799e945609"),
    // note_get_serial_number
    word!("0x59b3ea650232049bb333867841012c3694bd557fa199cd65655c0006edccc3ab"),
    // note_get_inputs_commitment_and_len
    word!("0x88004b9cd9571618c397637dc55a9fdf5a80421b1bbc1c964bf505b4796f410f"),
    // note_get_sender
    word!("0xf45bb5a348b67c886cb1577f78abf6c5100ebe953790882518849d29fbf7e5fb"),
    // note_get_script_root
    word!("0x66fb188ca538d9f8bc6fd1aedbd19336bf6e3a1c0ae67b5f725cbc9cb4f7867f"),
    // input_note_get_assets_info
    word!("0x0816c7215676487f3ce03d372bf5512afb528ab62466074921829d7d2974147c"),
    // output_note_get_assets_info
    word!("0x590e307c82e221f8145b6293ae990994194ce03cbcc324e64e11bd79dc8d35b2"),
    // input_note_get_recipient
    word!("0x1e612cf8aa3cca674363d9e1fb15c666a0cf2febc80bf9d7800920941133a3f4"),
    // output_note_get_recipient
    word!("0x46b39f143100c86135a7a4b0759d3db9348cd1e085965ae2878df9c539a67b83"),
    // input_note_get_metadata
    word!("0x4b0c2a8560a007abadd55013c3b3c620b2de2189c08109500ba46a4222b37d89"),
    // output_note_get_metadata
    word!("0xe0c67058b91fafee772f915f74f99b3d9d9856580eabc4660f6c6a00cffba466"),
    // tx_create_note
    word!("0x7b37e403cad0e89e597bdad0fadb27668fe38d98e62087cedcee9770a00da673"),
    // tx_get_input_notes_commitment
    word!("0xc3a334434daa7d4ea15e1b2cb1a8000ad757f9348560a7246336662b77b0d89a"),
    // tx_get_num_input_notes
    word!("0xfcc186d4b65c584f3126dda1460b01eef977efd76f9e36f972554af28e33c685"),
    // tx_get_output_notes_commitment
    word!("0x9c94ca576def549b2b77855ec9ee7bce460f275fbc196650040c93b34543a34d"),
    // tx_get_num_output_notes
    word!("0x0d9d5cca827893238181b973ec43af8ee4b4018dd32c8d2e85fd797d978c88c0"),
    // tx_get_block_commitment
    word!("0xe474b491a64d222397fcf83ee5db7b048061988e5e83ce99b91bae6fd75a3522"),
    // tx_get_block_number
    word!("0x297797dff54b8108dd2df254b95d43895d3f917ab10399efc62adaf861c905ae"),
    // tx_get_block_timestamp
    word!("0x7903185b847517debb6c2072364e3e757b99ee623e97c2bd0a4661316c5c5418"),
    // tx_start_foreign_context
    word!("0x86e95788b9f8990f31a60899ac4aa9f7aeaa6ddbd7d9fb99f36a0be0b156274c"),
    // tx_end_foreign_context
    word!("0xc91404440384adc5ece0771f1c096c2a46eac56648d7361854b9da3b917305e5"),
    // tx_get_expiration_delta
    word!("0x4c3ca7bb7dac8ae20aefe6ebe582499730cd5ffa3d2592ac88b83a4d72873089"),
    // tx_update_expiration_block_num
    word!("0xe32ef05186b19990499f8d8f5cb736966e795a73a8082e6d1fbddc9a0a199d6c"),
];
